-- AlterTable
ALTER TABLE `expo_Token` ADD COLUMN `area1` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `area2` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `area3` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `area4` VARCHAR(191) NOT NULL DEFAULT '';
